# Generated by Django 4.1.7 on 2023-03-29 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auctions_current_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='auction_id',
            field=models.ForeignKey(db_column='auction_id', default=0, on_delete=django.db.models.deletion.CASCADE, to='auctions.auctions'),
        ),
        migrations.AddField(
            model_name='comments',
            name='contents',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='comments',
            name='username',
            field=models.CharField(default='', max_length=16),
        ),
    ]
