# Generated by Django 4.1.7 on 2023-03-24 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bids_category_comments_auctions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctions',
            old_name='bid_start',
            new_name='starting_price',
        ),
        migrations.AlterField(
            model_name='auctions',
            name='category',
            field=models.CharField(choices=[(None, 'Select'), ('fashion', 'Fashion'), ('electornics', 'Electornics'), ('furniture', 'Furniture'), ('toys', 'Toys'), ('books', 'Books'), ('kitchen', 'Kitchen'), ('others', 'Others')], default='Select', max_length=32),
        ),
        migrations.AlterField(
            model_name='auctions',
            name='description',
            field=models.TextField(max_length=1000),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
