# Generated by Django 4.1.7 on 2023-03-29 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_comments_auction_id_comments_contents_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='auction_id',
            field=models.ForeignKey(db_column='auction_id', on_delete=django.db.models.deletion.CASCADE, to='auctions.auctions'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='contents',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='comments',
            name='username',
            field=models.CharField(max_length=16),
        ),
    ]
