# Generated by Django 4.1.7 on 2023-03-24 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_watchlist_alter_auctions_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WatchList',
        ),
        migrations.AlterField(
            model_name='auctions',
            name='title',
            field=models.CharField(max_length=64),
        ),
    ]
