# Generated by Django 4.1.7 on 2023-03-24 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_delete_watchlist_alter_auctions_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctions',
            name='username',
            field=models.CharField(default='klee0511', max_length=16),
        ),
    ]
